# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-03 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(max_length=50, verbose_name='\u516c\u53f8\u5730\u5740'),
        ),
    ]
