# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180803_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(max_length=50, verbose_name='\u516c\u53f8\u804c\u4f4d'),
        ),
    ]
