# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-03 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='\u4e0d\u80fd\u5f00\u5c0f\u5dee', max_length=300, verbose_name='\u8001\u5e08\u63d0\u9192'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_need_know',
            field=models.CharField(default='\u597d\u597d\u5b66\u4e60\uff0c\u5929\u5929\u5411\u4e0a', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
    ]
